// <auto-generated />
using System;
using CursoWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursoWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbcontex))]
    [Migration("20230607160914_AgregandoDatos")]
    partial class AgregandoDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CursoWebAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 6, 7, 12, 9, 14, 505, DateTimeKind.Local).AddTicks(1876),
                            FechaCreacion = new DateTime(2023, 6, 7, 12, 9, 14, 505, DateTimeKind.Local).AddTicks(1865),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa real",
                            Ocupantes = 5,
                            Tarifa = 250.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Detalle de la villa 2",
                            FechaActualizacion = new DateTime(2023, 6, 7, 12, 9, 14, 505, DateTimeKind.Local).AddTicks(1879),
                            FechaCreacion = new DateTime(2023, 6, 7, 12, 9, 14, 505, DateTimeKind.Local).AddTicks(1879),
                            ImagenUrl = "",
                            MetrosCuadrados = 80,
                            Nombre = "Villa real 2",
                            Ocupantes = 8,
                            Tarifa = 280.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
